### ISSUE TITLE
CivicInfoAPIKey.plist.template CivicInfoAPIKey.plist couldn't be opened

### ISSUE THREAD

**Issue by Frehiwet** [votinginfoproject/ios7-white-label-app#191]
Hi guys,

I am trying to run the project  by following the readme file but it is giving me error. Please see the attached snap-shots. Thanks

On Terminal 
<img width="571" alt="screen shot 2015-10-16 at 10 53 57 am" src="https://cloud.githubusercontent.com/assets/10555642/10545221/93e48e26-73f5-11e5-9a71-7eaa6c58baf0.png">

On XCode
<img width="618" alt="screen shot 2015-10-16 at 10 55 31 am" src="https://cloud.githubusercontent.com/assets/10555642/10545252/bc0c7512-73f5-11e5-94b5-5b768a26178c.png">

Path

<img width="1221" alt="screen shot 2015-10-16 at 10 25 26 am" src="https://cloud.githubusercontent.com/assets/10555642/10545361/5a6c8c6a-73f6-11e5-90ba-85460b18abea.png">

**Comment by CloudNiner** [comment]
Thanks for bringing this to our attention.

Looks like the `cp` command in the readme is wrong. Try:
```
cp CivicAPIKey.plist.template CivicAPIKey.plist
```

**Comment by Frehiwet** [comment]
Thanks, It worked!!!
